/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "博",
  "description": "记录点点滴滴",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/interview/",
      "relativePath": "interview/README.md",
      "key": "v-0fec9cc2",
      "path": "/interview/"
    },
    {
      "frontmatter": {},
      "regularPath": "/web/css/",
      "relativePath": "web/css/README.md",
      "key": "v-d145753e",
      "path": "/web/css/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/home.jpg?v=1",
        "actionText": "Get Started",
        "actionLink": "/node/",
        "features": [
          {
            "title": "day day up",
            "details": "记录每一天的进步, 一分耕耘，一分收获."
          },
          {
            "title": "程序员成长指北",
            "details": "专注 Node.js 技术栈分享，从 前端 到 Node.js 再到 后端数据库，祝您成为优秀的高级 Node.js 全栈工程师"
          },
          {
            "title": "koala",
            "details": "一个有趣的且乐于分享的人。座右铭：今天未完成的，明天完成。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-14f28a0e",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/web/html/",
      "relativePath": "web/html/README.md",
      "key": "v-5e5fa689",
      "path": "/web/html/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "前端",
        "items": [
          {
            "text": "html",
            "link": "/web/html/"
          },
          {
            "text": "css",
            "link": "/web/css/"
          }
        ]
      },
      {
        "text": "面试问题",
        "link": "/interview/"
      }
    ]
  }
}