/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "欧先森",
  "description": "=====",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/home.jpg?v=1",
        "actionText": "Get Started",
        "actionLink": "/web/html/",
        "features": [
          {
            "title": "day day up",
            "details": "记录每一天的进步, 耕耘，收获."
          },
          {
            "title": "程序员成长指北",
            "details": "专注 Node.js 技术栈分享，从 前端 到 Node.js 再到 后端数据库，祝您成为优秀的高级 Node.js 全栈工程师"
          },
          {
            "title": "koala",
            "details": "一个有趣的且乐于分享的人。座右铭：今天未完成的，明天完成。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3e73283b",
      "path": "/"
    },
    {
      "title": "此页记录了开发过程中遇到的bug及部分需求的实现",
      "frontmatter": {},
      "regularPath": "/bug/",
      "relativePath": "bug/README.md",
      "key": "v-15d3e3de",
      "path": "/bug/",
      "headers": [
        {
          "level": 2,
          "title": "此页记录了开发过程中遇到的bug及部分需求的实现",
          "slug": "此页记录了开发过程中遇到的bug及部分需求的实现"
        },
        {
          "level": 3,
          "title": "H5",
          "slug": "h5"
        },
        {
          "level": 3,
          "title": "小程序",
          "slug": "小程序"
        }
      ]
    },
    {
      "title": "Phaser文档属性与API整理",
      "frontmatter": {},
      "regularPath": "/interview/",
      "relativePath": "interview/README.md",
      "key": "v-0acfd504",
      "path": "/interview/",
      "headers": [
        {
          "level": 2,
          "title": "Phaser文档属性与API整理",
          "slug": "phaser文档属性与api整理"
        },
        {
          "level": 3,
          "title": "准备工作",
          "slug": "准备工作"
        },
        {
          "level": 3,
          "title": "一：初始化游戏",
          "slug": "一-初始化游戏"
        },
        {
          "level": 3,
          "title": "二：API",
          "slug": "二-api"
        },
        {
          "level": 3,
          "title": "三：一些静态属性",
          "slug": "三-一些静态属性"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/web/css/",
      "relativePath": "web/css/README.md",
      "key": "v-b0ca22ba",
      "path": "/web/css/"
    },
    {
      "title": "这是我的首页",
      "frontmatter": {},
      "regularPath": "/web/html/",
      "relativePath": "web/html/README.md",
      "key": "v-55d8074b",
      "path": "/web/html/",
      "headers": [
        {
          "level": 3,
          "title": "这是我的首页",
          "slug": "这是我的首页"
        }
      ]
    },
    {
      "title": "Phaser实例编写",
      "frontmatter": {},
      "regularPath": "/Phaser/",
      "relativePath": "Phaser/README.md",
      "key": "v-43ba2ffe",
      "path": "/Phaser/",
      "headers": [
        {
          "level": 2,
          "title": "Phaser实例编写",
          "slug": "phaser实例编写"
        },
        {
          "level": 3,
          "title": "准备工作",
          "slug": "准备工作"
        },
        {
          "level": 3,
          "title": "一：搭建初始结构",
          "slug": "一-搭建初始结构"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "bug",
        "link": "/bug/"
      },
      {
        "text": "Phaser学习笔记",
        "link": "/Phaser/"
      },
      {
        "text": "前端",
        "items": [
          {
            "text": "html",
            "link": "/web/html/"
          },
          {
            "text": "css",
            "link": "/web/css/"
          }
        ]
      },
      {
        "text": "面试问题",
        "link": "/interview/"
      }
    ]
  }
}